print ('世界那么大，我想去看看'[7:-1])
print(0xf2)
print('\nPython')
a=1
b=2
c=3
(a,b,c)=(c,a,b)
print(a,b,c)
print(12&8)
d= input('请输入一个四位的整数：')
print(int(d[0:-3]))
print(int(d[1:-2]))
print(int(d[2:-1]))
print(int(d[3]))
print(eval(d[0:-3]))
print(eval(d[1:-2]))
print(eval(d[2:-1]))
print(eval(d[3]))
num_original = input('请输入一个四位的整数：')
num = int(num_original)
num_1 = int(num%10)
num_2 = int(num//10%10)
num_3 = int((num%1000-num_2-num_1)/100)
num_4 = int(num_original[0])
print('个位上的数为：',num_1,sep='')
print('十位上的数为：',num_2,sep='')
print('百位上的数为：',num_3,sep='')
print('千位上的数为：',num_4,sep='')

daddy_high = float(input('请输入父亲的身高：'))
mom_high = eval(input('请输入母亲的身高：'))
your_high = 0.54*(daddy_high+mom_high)
print('你的身高是：',your_high,'厘米',sep='')